name: Secure App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run Bandit (Python security linter)
      run: |
        pip install bandit
        bandit -r app || true

    - name: Build Docker image
      run: |
        docker build -t secure-flask-app .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'secure-flask-app'
        format: 'table'
        exit-code: '0'

